__include__: ['base_config.yaml']

general:
  out_dir: '~/out_dir/gpt2_124m_owt'

logging:
  project_name: gpt2_124m_owt

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/val.bin'

