__include__: ['base_config.yaml']

general:
  out_dir: '~/out_dir/gpt2_124m_owt'

logging:
  project_name: 'gpt2_124m_owt_24xh100'
  enable_wandb: true
  enable_summaries: true
  run_name: 'gpt2_124m_owt'  # select random name
  run_description: 'GPT2 124M on OpenWebText'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/val.bin'

