__include__: ['base_config.yaml']

# Config from Karpathy's llm.c:
# https://github.com/karpathy/llm.c/discussions/481

general:
  project_name: 'gpt2_owt'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/val.bin'

training:
  device_batch_size: 64
  max_steps: 19074
  global_batch_size: 512

scheduler:
  module: 'nanugpt.schedulers.linear.get_scheduler'
  module_kwargs:
    warmup_iters: 700
    end_factor: 1.0E-3

eval:
  eval_every: 250
  eval_iters: 200 # number of samples to evaluate for dataset
  save_checkpoint: true
  checkoint_after: 0 # starts saving checkpoint after these steps
  checkpoint_every_hr: 200 # multiple of eval_every, save checkpoint after these steps from last checkpoint when val loss is better
  checkpoint_keep_best: false # keep only the best checkpoint, otherwise keep all with  _{step}.pt