__include__: ['base_config.yaml']

general:
  project_name: 'gpt2o_tinystories'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/tinystories_v2/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/tinystories_v2/tiktoken/validation.bin'

training:
  max_steps: 37500 # 37500 for ctx=1024



