__include__: ['base_config.yaml']

general:
  out_dir: '~/out_dir/gpt2_124m_tinystories'

logging:
  project_name: 'gpt2_124m_tinystories'
  enable_wandb: true
  enable_summaries: true
  run_name: 'gpt124m_tinystories_same_as_owt'  # null -> select random name
  run_description: 'Same model and params as OWT, GPT124M tinystories using gpt2 tokenizer and bfloat16'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/tinystories_v2/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/tinystories_v2/tiktoken/validation.bin'

