__include__: ['base_config.yaml']

general:
  project_name: 'gpt2o_tinystories'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/tinystories_v2/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/tinystories_v2/tiktoken/validation.bin'

training:
  #device_batch_size: 60
  max_steps: 16000 # 37500 for ctx=1024
  #global_batch_size: 480

optimizer:
  module_kwargs:
    learning_rate: 600.0E-4 # LR found by LRRT

scheduler:
  module: 'nanugpt.schedulers.linear.get_scheduler'
  module_kwargs:
    warmup_iters: 1500
    end_factor: 1.0E-3


