__include__: ['base_config.yaml']

general:
  out_dir: '~/out_dir/gpt2_124m_wikitext-103'

logging:
  project_name: 'gpt2_124m_wikitext-103'
  enable_wandb: true
  enable_summaries: true
  run_name: 'gpt124m_wikitext103_same_as_owt'  # select random name
  run_description: 'Same model and params as OWT, GPT124M WikiText-103 using gpt2 tokenizer and bfloat16'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/wikitext-103-raw-v1/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/wikitext-103-raw-v1/tiktoken/validation.bin'
    tokenized_test_path: '$DATA_ROOT/tokenized/wikitext-103-raw-v1/tiktoken/test.bin'

