
training:
  max_steps: 100

scheduler:
  _inherit: false
  module: 'nanugpt.schedulers.lr_range_test.get_scheduler'
  module_kwargs:
    max_steps: '_copy: /training/max_steps'
    range_coeff: 5.0

eval:
  eval_every: 1
  eval_iters: 200 # number of samples to evaluate for dataset
  save_checkpoint: false
