__include__: ['base_config.yaml']

general:
  project_name: 'llama2_owt'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/openwebtext/llama2/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/openwebtext/llama2/val.bin'

