__include__: ['base_config.yaml']

general:
  project_name: 'llama2_tinystories'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/tinystories_v2/llama2/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/tinystories_v2/llama2/validation.bin'

