__include__: ['base_config.yaml']

general:
  out_dir: '~/out_dir/llama2_124m_tinystories'

logging:
  project_name: 'tinyllama_124m_tinystories'
  enable_wandb: true
  enable_summaries: true
  run_name: 'Llama2-124m_tinystories_tokgpt2'  # null -> select random name
  run_description: 'Llama2-124m tinystories using llama2 tokenizer and bfloat16'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/tinystories_v2/llama2/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/tinystories_v2/llama2/validation.bin'

