__include__: ['base_config.yaml']

general:
  out_dir: '~/out_dir/llama2_124m_wikitext103'

logging:
  project_name: 'tinyllama_124m_wikitext103'
  enable_wandb: true
  enable_summaries: true
  run_name: 'llama2-124m_wikitext103'  # select random name
  run_description: 'Llama2-124M WikiText-103 using llama2 tokenizer and bfloat16'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/wikitext-103-raw-v1/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/wikitext-103-raw-v1/tiktoken/validation.bin'
    tokenized_test_path: '$DATA_ROOT/tokenized/wikitext-103-raw-v1/tiktoken/test.bin'
