__include__: ['defaults.yaml']

data:
  training_fraction: 0.5
  val_fraction: null # if null, use 1 - training_fraction
  prime: 97

training:
  weight_decay: 0.05     # weight_decay=1 makes things unstable with lots of loss spikes
  num_steps: 50000
