__include__: ['base_config.yaml']

data:
  module_kwargs:
    training_fraction: 0.5
    val_fraction: null # if null, use 1 - training_fraction
    prime: &prime 50021

tokenizer:
  module_kwargs:
    prime: *prime

optimizer:
  module_kwargs:
    weight_decay: 0.1     # weight_decay=1 makes convergence much faster and original graph is not reproducible

training:
  num_steps: 1000000    # 1e5 is not enough when weight_decay=0.0
