__include__: ['base_config.yaml']

model:
  module: 'nanugpt.models.tiny_transformer.get_model'

loss:
  module: 'nanugpt.losses.grokking_loss.get_loss'

tokenizer:
  module: 'nanugpt.tokenizers.grokking_tokenizer.get_tokenizer'

optimizer:
  module: 'nanugpt.optimizers.adam_w.get_optim'

scheduler:
  module: 'nanugpt.schedulers.linear.get_scheduler'

