__include__: ['defaults.yaml']

data:
  training_fraction: 0.5
  val_fraction: null # if null, use 1 - training_fraction
  prime: 223

training:
  weight_decay: 0.1     # weight_decay=1 makes convergence much faster and original graph is not reproducible
  num_steps: 3000    # 1e5 is not enough when weight_decay=0.0
