__include__: ['base_config.yaml']

tokenizer:
  module: 'nanugpt.tokenizers.hf_tokenizer.get_tokenizer_factory'
  module_kwargs:
    hf_path: 'NousResearch/Llama-2-7b-hf'
    token: '$HF_AUTH_TOKEN'
    fix_pad_token: false

data:
  hf_name_path: '$DATA_ROOT/datasets/openwebtext'
  tokenized_out_dir: '$DATA_ROOT/tokenized/openwebtext/llama2/'

  val_fraction: 0.0005
  text_column: null




