__include__: ['base_config.yaml']

general:
  project_name: 'tokenization_openwebtext'

tokenizer:
  module: 'nanugpt.tokenizers.tiktoken_wrap.get_tokenizer_factory'
  module_kwargs:
    encoding_name: 'gpt2'

data:
  hf_name_path: '$DATA_ROOT/datasets/openwebtext'
  tokenized_out_dir: '$DATA_ROOT/tokenized/openwebtext/tiktoken/'

  val_fraction: 0.0005
  text_column: null




