__include__: ['base_config.yaml']

tokenizer:
  module: 'nanugpt.tokenizers.byte_tokenizer.get_tokenizer_factory'
  module_kwargs:
    encoding_name: 'utf-8'

data:
  hf_name_path: '$DATA_ROOT/datasets/tinystories/tinystories_v2'
  tokenized_out_dir: '$DATA_ROOT/tokenized/tinystories_v2/byte/'





