__include__: ['base_config.yaml']

tokenizer:
  module: 'nanugpt.tokenizers.tiktoken_wrap.get_tokenizer_factory'
  module_kwargs:
    encoding_name: 'cl100k_base'

data:
  hf_name_path: '$DATA_ROOT/datasets/tiny_stories/tinystories_v2'
  tokenized_out_dir: '$DATA_ROOT/tokenized/tinystories_v2/tiktoken/'





