__include__: ['base_config.yaml']

general:
  project_name: 'tokenization_wikitext-103'

tokenizer:
  module: 'nanugpt.tokenizers.tiktoken_wrap.get_tokenizer_factory'
  module_kwargs:
    encoding_name: 'gpt2'

data:
  hf_name_path: '$DATA_ROOT/datasets/wikitext-103-raw-v1'
  tokenized_out_dir: '$DATA_ROOT/tokenized/wikitext-103-raw-v1/tiktoken/'





