# transformer
num_layers: 2
dim_model: 128
num_heads: 4

# general
device: ''            # auto select or cpu, cuda
seed: 56 # 42 is good seed, 56 is bad seed
data_loader_seed: 0 # 8 is good seed, 7 is bad seed
out_dir: '~/out_dir/grokking'
log_filename: 'seed_search_v1_baseline.txt'
allow_overwrite_log: true

# data
operation: 'x/y'
training_fraction: 0.5
val_fraction: null # if null, use 1 - training_fraction
batch_size: 512

# training
learning_rate: 1.0E-3

# eval
eval_every: 1000000
eval_batch_size: 32768 # 2^15=32768