# default config is designed for GPT-124M params and OpenWebText dataset

general:
  device_type: 'cuda'            # auto select if blank or cpu, cuda
  backend: 'nccl'       # nccl, gloo, mpi, horovod)
  dtype: 'bfloat16'         # float32, float16, bfloat16
  torch_compile: true # will not compile if Python > 3.11, torch < 2.1.0 or Windows
  seed: 42
  enable_distributed: true
  out_dir: '~/out_dir/experiment'

logging:
  enable_wandb: false
  project_name: nil
  run_name: nil  # select random name
  run_description: nil
  log_dir: '~/out_dir/experiment'
  log_filename: 'log.txt'
  allow_overwrite_log: true
  metrics_type: 'classification'
  enable_summaries: true

model:
  module: 'gptplay.models.nanogpt.get_model'
  # GPT-124M config from NanoGPT
  n_layer: 12
  n_embd: 768
  n_head: 12
  context_length: &context_length 1024
  # set bias to 0.0 for pre-training, 0.1+ for finetuning
  # PyTorch default for bias is true
  ffn_bias: false # pytorch default
  attn_proj_bias: false # for projection layers in attention
  attn_kv_bias: false # for kv in attention
  attn_dropout: 0.0 # dropout for attention layer
  ffn_dropout: 0.0 # dropout for feedforward layer

loss:
  module: 'gptplay.losses.autoregressive_loss.get_loss'

data:
  module: 'gptplay.datasets.on_demand_tokenization.get_data'
  train_batch_size: 12
  eval_batch_size: 32768 # 2^15=32768
  data_loader_seed: 8
  context_length: *context_length

tokenizer:
  module: 'gptplay.tokenizers.tiktoken.get_tokenizer'

training:
  num_steps: 600000    # for OpenWebText/9B tokens
  enable_train_log: false
  log_every: 20 # after how many steps to log just train loss
  grad_clip: 1.0 # disabled if 0.0
  gradient_accumulation_steps: 40 # will be automatically divided by GPU count

optimizer:
  module: 'gptplay.optimizers.adamw_wd.get_optim'
  learning_rate: 6.0E-4
  weight_decay: 0.1     # weight_decay=1 makes convergence much faster and original graph is not reproducible
  beta1: 0.9
  beta2: 0.95
  eps: 1.0E-8 # pytorch default

scheduler:
  module: 'gptplay.schedulers.nanogpt_cosine.get_scheduler'
  warmup_iters: 2000
  lr_decay_iters: 600000
  min_lr: 6.0E-5

eval:
  eval_every: 1000
  eval_iters: 200 # number of samples to evaluate for dataset
  save_checkpoint: true
  checkoint_after: 2000 # starts saving checkpoint after these steps
  checkpoint_every: 10 # multiple of eval_iters, save checkpoint after these steps from last checkpoint when val loss is better
