__include__: ['defaults.yaml', 'wandb.yaml']

# data
prime: 50021

# training
weight_decay: 0.1     # weight_decay=1 makes convergence much faster and original graph is not reproducible
num_steps: 1000000    # 1e5 is not enough when weight_decay=0.0
